spring:
  mandatory-file-encoding: UTF-8
  jmx:
    enabled: false
  data:
    mongodb:
      database: kukulkan
      host: mongodb
      port: 27017
server:
  port: 8080
kukulkan:
  outputdir: /var/www/html/kukulkan/
logging:
  level:
    root: info
    org.springframework.web: false
    org.hibernate: false
    org.hibernate.SQL: false
    file: kukulkan.log